name: CI-CD-dev
on: 
  push:  
    branches:  
      - dev
    
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  actions: write

jobs: 
  
  build:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
    - name: Checkout source code  
      uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
     
    - name: Inject slug/short variables  
      uses: rlespinasse/github-slug-action@v4
    - name: Upload artifact  
      uses: actions/upload-artifact@v3  
      with:  
        name: sample-java-app-${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}  
        path: ./target
          
  deploy:  
    needs : build
    if: always()
    runs-on: ubuntu-latest  
  
    steps:
      - name: Inject slug/short variables  
        uses: rlespinasse/github-slug-action@v4 
      - name: Download artifact  
        uses: actions/download-artifact@v3  
        with:  
          name: personal-website-angular-${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}  
          path: './target'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ls
